version: 2
updates:
  - package-ecosystem: nuget
    directory: /tools/iostore_inventory
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
