return {
    ["Data.Excel.LanguageData.StringDB_CN_Data"] = {
        ["Like {\"愚者\",\"世界\"}, can match \"Fool and World\", but cannot match \"World and Fool\""] = "Like {\"Fool\",\"World\"}, this can match \"Fool and World\", but cannot match \"World and Fool\"",
        ["{\"技能类型%i\"}"] = "{\"Skill Type %i\"}",
        ["{\"技能标签%i\"}"] = "{\"Skill Tag %i\"}",
        ["{\"技能ID%i\"}"] = "{\"Skill ID %i\"}",
        ["{\"Buff类型%i\"}"] = "{\"Buff Type %i\"}",
        ["{\"Buff标签%i\"}"] = "{\"Buff Tag %i\"}",
        ["{\"怪物ID%i\"}"] = "{\"Monster ID %i\"}",
        ["{\"场景ID%i\"}"] = "{\"Scene ID %i\"}",
        ["{\"槽位编号\"=\"技能ID\"}"] = "{\"Slot Number\"=\"Skill ID\"}",
        ["{\"X偏移cm\",\"Y偏移cm\",\"Z偏移cm\"}"] = "{\"X Offset cm\",\"Y Offset cm\",\"Z Offset cm\"}",
        ["{{\"第%i个子弹的X偏移cm\",\"第%i个子弹的Y偏移cm\",\"第%i个子弹的Z偏移cm\"}}"] = "{{\"X Offset of Projectile %i cm\",\"Y Offset of Projectile %i cm\",\"Z Offset of Projectile %i cm\"}}",
        ["{\"第%i个子弹的额外Yaw角\"}"] = "{\"Extra Yaw Angle of Projectile %i\"}",
        ["{\"第%i个子弹的额外Pitch角\"}"] = "{\"Extra Pitch Angle of Projectile %i\"}",
        ["{\"第%i批子弹发射时间点\"}"] = "{\"Firing Time of Projectile Batch %i\"}",
        ["{\"标签%i\"}"] = "{\"Tag %i\"}",
        ["{\"标签%i清除Buff数量\"}"] = "{\"Number of Buffs Cleared by Tag %i\"}",
        ["{\"类型%i\"}"] = "{\"Type %i\"}",
        ["{\"坐标X\",\"坐标Y\",\"坐标Z\"}"] = "{\"X Coordinate\",\"Y Coordinate\",\"Z Coordinate\"}",
        ["{{\"目标属性名(比如Hp)\",\"源属性名(比如MaxHp)\",\"属性恢复方式(0:按源属性的百分比；1:按绝对数值)\",\"数值(绝对的数值或者百分比值)\"}}"] = "{{\"Target Attribute Name (e.g. Hp)\",\"Source Attribute Name (e.g. MaxHp)\",\"Attribute Recovery Method (0: percentage of source attribute; 1: absolute value)\",\"Value (absolute value or percentage)\"}}",
        ["{\"权重%i\"}"] = "{\"Weight %i\"}",
        ["{{\"BuffID%i\",\"Buff层数%i\",\"Buff时长%i\"}}"] = "{{\"Buff ID %i\",\"Buff Stacks %i\",\"Buff Duration %i\"}}",
        ["{{\"子弹%iX偏移cm\",\"子弹%iY偏移cm\",\"子弹%iZ偏移cm\"}}"] = "{{\"Projectile %i X Offset cm\",\"Projectile %i Y Offset cm\",\"Projectile %i Z Offset cm\"}}",
        ["{\"子弹%i额外Yaw\"}"] = "{\"Projectile %i Extra Yaw\"}",
        ["{\"子弹%i额外Pitch\"}"] = "{\"Projectile %i Extra Pitch\"}",
        ["{\"子弹%i发射时间点\"}"] = "{\"Projectile %i Firing Time\"}",
        ["{\"Buff标签%i驱散数量\"}"] = "{\"Dispel Count for Buff Tag %i\"}",
        ["{\"旋转量1\",\"旋转量2\",\"旋转量3\"}"] = "{\"Rotation Amount 1\",\"Rotation Amount 2\",\"Rotation Amount 3\"}",
        ["{\"法术场ID%i\"}"] = "{\"Spell Field ID %i\"}",
        ["{\"%i号法术场的数量\"}"] = "{\"Count of Spell Field %i\"}",
        ["{\"第%i个位移终点\"}"] = "{\"Displacement Endpoint %i\"}",
        ["{\"第%i个法术场ID\"}"] = "{\"Spell Field ID %i\"}",
        ["{{\"第%i个属性名\",\"修改值（关于Hp的表达式）\"}}"] = "{{\"Attribute Name %i\",\"Modified Value (Expression Relative to Hp)\"}}",
        ["{\"第%i个属性名\"}"] = "{\"Attribute Name %i\"}",
        ["{\"可缺省\"}"] = "{\"Optional\"}",
        ["{\"默认为false。若为true，上面4个限制无效，但白名单生效\"}"] = "{\"Defaults to false. If true, the four restrictions above are disabled, but the allowlist remains active\"}",
        ["{\"陷阱ID%i\"}"] = "{\"Trap ID %i\"}",
        ["{\"%i号陷阱的数量\"}"] = "{\"Count of Trap %i\"}",
        ["{\"Mesh名称\"}"] = "{\"Mesh Name\"}",
        ["{{\"第%i个按键的资源名\",\"对应的技能ID\",\"对应的键盘按键（仅可填Q/W/E/R/A/S/D/F之一）\"}}"] = "{{\"Resource Name for Key %i\",\"Corresponding Skill ID\",\"Corresponding Keyboard Key (must be one of Q/W/E/R/A/S/D/F)\"}}",
        ["{{\"技能ID%i\",\"增加等级\"}}"] = "{{\"Skill ID %i\",\"Levels Added\"}}",
        ["{{\"技能Type（参看悬停注释）\",\"增加等级\"}}"] = "{{\"Skill Type (see hover tooltip)\",\"Levels Added\"}}",
        ["{{\"第%i个属性名\",\"修改值\"}}"] = "{{\"Attribute Name %i\",\"Modified Value\"}}",
        ["{缺省就是crazy表的数据；如果填写了会覆写表格中的数据}"] = "{By default, uses data from the crazy table; if specified, overrides the data in the table}",
        ["{\"填0代表上当前装配的默认坐骑\"}"] = "{\"Enter 0 to use the default mount from the current loadout\"}",
    },
    ["Data.Excel.LanguageData.StringDB_CN_Data_aura"] = {
        ["黄铜书_子嗣守护_炼金产物光环_地脉"] = "Brass Book_Offspring Protection_Alchemy Product Aura_Ley Line",
    },
    ["Data.Excel.LanguageData.StringDB_CN_Data_buffappear"] = {
        ["粉碎灵魂"] = "Soul Shatter",
        ["副本69"] = "Dungeon 69",
        ["副本69中R"] = "R in Dungeon 69",
        ["副本74中R"] = "R in Dungeon 74",
        ["愚者庇佑"] = "The Fool's Blessing",
        ["愚者的恩赐"] = "The Fool's Boon",
        ["愚者的赞许"] = "The Fool's Approval",
        ["愚者的注视"] = "The Fool's Gaze",
        ["愚者的叹息"] = "The Fool's Sigh",
        ["摇铃提示"] = "Bell-Ringing Alert",
    },
    ["Data.Excel.LanguageData.StringDB_CN_Data_buffdata"] = {
        ["粉碎灵魂"] = "Soul Shatter",
        ["副本69"] = "Dungeon 69",
        ["副本69中R"] = "R in Dungeon 69",
        ["愚者庇佑"] = "The Fool's Blessing",
        ["吞噬灵魂+标记Buff"] = "Soul Devour + Mark Buff",
        ["生命手杖：初次治疗标记"] = "Staff of Life: Initial Heal Marker",
        ["愚者的赞许"] = "The Fool's Approval",
        ["愚者的注视"] = "The Fool's Gaze",
        ["愚者的叹息"] = "The Fool's Sigh",
        ["愚者之礼-飞升计时"] = "The Fool's Gift - Ascension Timer",
    },
    ["Data.Excel.LanguageData.StringDB_CN_Data_debug"] = {
        ["—技能_幻影_重剑_南北_逆时针"] = "—Skill_Phantom_Greatsword_North-South_Counterclockwise",
        ["通用-神降龙-变天"] = "Generic-Divine Descent Dragon-Weather Change",
        ["封印物-蠕动的饥饿-脱手技能对怪"] = "Sealed Artifact-Creeping Hunger-Hands-Off Skill Against Monsters",
    },
    ["Data.Excel.LanguageData.StringDB_CN_Data_guide"] = {
        ["使用技能<Highlight>共鸣</>，解除碎片封锁"] = "Use the <Highlight>Resonance</> skill to unseal the fragment.",
    },
    ["Data.Excel.LanguageData.StringDB_CN_Data_itemnormal"] = {
        ["恭喜你，幸运儿。被祂眷顾，是荣幸，也是开始。愿你在愚者的注视与庇佑下，旅途愉快。"] = "Congratulations, lucky one. To receive His favor is both an honor and a beginning. May your journey be a pleasant one under The Fool's watchful gaze and protection.",
        ["使用后获得称号:<Highlight>锈蚀飞轮（7天）</>"] = "Use to obtain the title: <Highlight>Rusted Flywheel (7 Days)</>",
    },
    ["Data.Excel.LanguageData.StringDB_CN_Data_itemoutlook"] = {
        ["永不流动的黄昏凝结于发梢，哪怕此身沐浴落日，仍有唤醒黎明之志。"] = "Dusk, forever stilled, congeals at the tips of the hair. Though this form bathes in the setting sun, it still bears the resolve to awaken the dawn.",
        ["伴随红月而来的疯狂呓语，小说家颂念了愚者的尊名，此时她尚且不知，这将是一场跨越家族和历史的旅行。"] = "Amid the mad whispers that came with the crimson moon, the novelist recited the honorific name of The Fool. Little did she know then that this would become a journey spanning family and history.",
        ["使用后可获得<Highlight>对应展台贴纸</>\n重复获取将自动分解为绑定苏勒×10000"] = "Use to obtain the <Highlight>corresponding display stand sticker</>\nDuplicates will automatically be dismantled into Bound Sooles ×10,000",
        ["<Highlight>工艺：</>探险工装\n铁轨延伸至远方，工具叮当作响，一场蒸汽与引擎声交织的铁道之旅自此展开。"] = "<Highlight>Craft:</> Adventurer's Workwear\nThe rails stretch into the distance and tools ring out; thus begins a railway journey woven from steam and the roar of engines.",
        ["<Highlight>工艺：</>压纹皮革\n永不流动的黄昏停滞于肩甲，哪怕此身沐浴落日，仍有唤醒黎明之志。"] = "<Highlight>Craft:</> Embossed Leather\nDusk, forever stilled, lies frozen upon the pauldrons. Though this form bathes in the setting sun, it still bears the resolve to awaken the dawn.",
        ["<Highlight>工艺：</>橄榄丝绒・金纹提花・刺绣长裙\n伴随红月而来的疯狂呓语，小说家颂念了愚者的尊名，此时她尚且不知，这将是一场跨越家族和历史的旅行。"] = "<Highlight>Craft:</> Olive Velvet・Gold-Patterned Jacquard・Embroidered Gown\nAmid the mad whispers that came with the crimson moon, the novelist recited the honorific name of The Fool. Little did she know then that this would become a journey spanning family and history.",
        ["<Highlight>工艺：</>童话礼服\n即便是误入的来客，也请遵从着装的礼仪。换上蓝黑菱格的俏皮礼服，加入怪诞奇妙的茶会。"] = "<Highlight>Craft:</> Fairy-Tale Dress\nEven guests who wander in by mistake must observe the dress code. Slip into a playful blue-and-black diamond-patterned dress and join the strange and wondrous tea party.",
        ["<Highlight>工艺：</>精工银链\n即便是误入的来客，也请遵从着装的礼仪。换上蓝黑菱格的俏皮礼服，加入怪诞奇妙的茶会。"] = "<Highlight>Craft:</> Finely Wrought Silver Chain\nEven guests who wander in by mistake must observe the dress code. Slip into a playful blue-and-black diamond-patterned dress and join the strange and wondrous tea party.",
        ["<Highlight>工艺：</>蓝白蕾丝・俏皮兔耳・童话礼服\n即便是误入的来客，也请遵从着装的礼仪。换上蓝白蕾丝的俏皮礼服，加入怪诞奇妙的茶会。"] = "<Highlight>Craft:</> Blue-and-White Lace・Playful Bunny Ears・Fairy-Tale Dress\nEven guests who wander in by mistake must observe the dress code. Slip into a playful blue-and-white lace dress and join the strange and wondrous tea party.",
        ["即便是误入的来客，也请遵从着装的礼仪。换上蓝白蕾丝的俏皮礼服，加入怪诞奇妙的茶会。"] = "Even guests who wander in by mistake must observe the dress code. Slip into a playful blue-and-white lace dress and join the strange and wondrous tea party.",
        ["<Highlight>工艺：</>蓝白蕾丝・童话礼服\n即便是误入的来客，也请遵从着装的礼仪。换上蓝白蕾丝的俏皮礼服，加入怪诞奇妙的茶会。"] = "<Highlight>Craft:</> Blue-and-White Lace・Fairy-Tale Dress\nEven guests who wander in by mistake must observe the dress code. Slip into a playful blue-and-white lace dress and join the strange and wondrous tea party.",
        ["<Highlight>工艺：</>蓝白蕾丝\n即便是误入的来客，也请遵从着装的礼仪。换上蓝白蕾丝的俏皮礼服，加入怪诞奇妙的茶会。"] = "<Highlight>Craft:</> Blue-and-White Lace\nEven guests who wander in by mistake must observe the dress code. Slip into a playful blue-and-white lace dress and join the strange and wondrous tea party.",
        ["<Highlight>工艺：</>蓝白蕾丝・俏皮兔耳\n即便是误入的来客，也请遵从着装的礼仪。换上蓝白蕾丝的俏皮礼服，加入怪诞奇妙的茶会。"] = "<Highlight>Craft:</> Blue-and-White Lace・Playful Bunny Ears\nEven guests who wander in by mistake must observe the dress code. Slip into a playful blue-and-white lace dress and join the strange and wondrous tea party.",
        ["<Highlight>工艺：</>亚麻棉纺・田园便服\n于莫尔斯小镇的金色麦浪中，拾取一段曾经的温柔时光。"] = "<Highlight>Craft:</> Linen-Cotton Weave・Country Casualwear\nAmid the golden waves of wheat in Morse Town, gather up a fragment of bygone tenderness.",
    },
    ["Data.Excel.LanguageData.StringDB_CN_Data_itemtask"] = {
        ["魔药"] = "Potion",
    },
    ["Data.Excel.LanguageData.StringDB_CN_Data_manor"] = {
        ["脚步声在木质阶梯上更显清亮，连接不同楼层。"] = "Footsteps ring crisp and clear upon the wooden staircase linking the different floors.",
    },
    ["Data.Excel.LanguageData.StringDB_CN_Data_newbietask"] = {
        ["自由装修城堡，参与各种闲趣活动，享受疯狂世界中的片刻宁静。"] = "Decorate the castle as you please, take part in all manner of leisurely activities, and savor a moment of peace in this mad world.",
    },
    ["Data.Excel.LanguageData.StringDB_CN_Data_oldtalk"] = {
        ["是"] = "Yes",
    },
    ["Data.Excel.LanguageData.StringDB_CN_Data_skill"] = {
        ["调动对知识的感知力，将自身钻研的格斗技巧拆解、融合，通过体验起手招式，深入武学精髓。当再度攻击时，将会留下一道源自知识的格斗残影。\n吸收残影后，可使武力加3，直觉加1。"] = "Draw upon your perception of knowledge to break down and merge the combat techniques you have studied. Experience their opening moves to delve into the essence of martial arts. Your next attack leaves behind a combat afterimage born of knowledge.\nAbsorbing the afterimage grants +3 Might and +1 Intuition.",
    },
    ["Data.Excel.LanguageData.StringDB_CN_Data_skill3"] = {
        ["在目标位置召唤窥秘之眼链接目标，每0.5秒对目标造成*d伤害并使目标减速25%。链接最多持续4秒，目标远离窥秘之眼一定距离后链接会提前断开。"] = "Summon an Eye of Mystery at the target location to link to the target, dealing *d damage every 0.5 seconds and slowing the target by 25%. The link lasts up to 4 seconds and breaks early if the target moves too far from the Eye of Mystery.",
    },
    ["Data.Excel.LanguageData.StringDB_CN_Data_talk"] = {
        ["我？"] = "Me?",
    },
    ["Data.Excel.LanguageData.StringDB_CN_Data_talkother"] = {
        ["扮演·占卜家"] = "Acting · Seer",
    },
    ["Data.Excel.LanguageData.StringDB_CN_Data_traingame"] = {
        ["如果下一站<LightHighlight>是【食铺】</>，当前持有的金色物品数量均增加<LightHighlight>60%</>"] = "If the next stop <LightHighlight>is [Food Stall]</>, increase the quantity of all golden items currently held by <LightHighlight>60%</>",
    },
    ["Data.Excel.LanguageData.StringDB_CN_Data_trap"] = {
        ["穿越边界时，有*d**的基础概率被施加*f秒<HyperLink stylename=\"M_Link\" u=\"7\">禁锢</>"] = "When crossing the boundary, there is a base *d** chance to be <HyperLink stylename=\"M_Link\" u=\"7\">Immobilized</> for *f seconds",
    },
}
